import { SINAN_DICTIONARY, SINAN_GROUPS, DEFAULT_SINAN_FIELD } from './sinan_data';

export const FIELD_DICTIONARY = SINAN_DICTIONARY;
export const FIELD_GROUPS = SINAN_GROUPS;
export const DEFAULT_FIELD_DEF = DEFAULT_SINAN_FIELD;
