export interface GeoLocation {
  regiao_saude: string;
  ra: string; // Região Administrativa
  bairro: string;
  descricao: string;
  id_bairro: string;
}

// Data parsed from the provided text
export const DF_GEO_DB: GeoLocation[] = [
  { regiao_saude: 'Região Sudoeste', ra: 'Água Quente', bairro: 'Setor Habitacional Água Quente', descricao: 'Condomínios e residenciais: Buritis I e II, Dom Francisco, Dom Pedro, Galiléia, Guarapari, Nova Betânia, Rodovia DF-280, São Francisco, Salomão Elias.', id_bairro: '242' },
  { regiao_saude: 'Região Sudoeste', ra: 'Águas Claras', bairro: 'Águas Claras Vertical', descricao: 'Administração Regional de Águas Claras. Avenidas: Araucárias (até a Faculdade Processus), Castanheiras, Jequitibá, Famboyant, Parque Águas Claras. CAESB - Sede. Colônia Agrícola Governador. Parque Ecológico de Águas Claras. Quadras: 101 a 107, 201 a 210, 301. Residenciais: Península, Via Enseada. Teatro da Árvore. Unieuro.', id_bairro: '198' },
  { regiao_saude: 'Região Sudoeste', ra: 'Águas Claras', bairro: 'IGN Águas Claras', descricao: 'Null', id_bairro: '203' },
  { regiao_saude: 'Região Sudoeste', ra: 'Arniqueira', bairro: 'ADE', descricao: 'ADE (antiga ADE Águas Claras).', id_bairro: '199' },
  { regiao_saude: 'Região Sudoeste', ra: 'Arniqueira', bairro: 'Areal', descricao: 'Areal, QS 6 a 11.', id_bairro: '200' },
  { regiao_saude: 'Região Sudoeste', ra: 'Arniqueira', bairro: 'Vereda da Cruz', descricao: 'Colônia Agrícola Vereda da Cruz. Avenida Vereda da Cruz (até o final)', id_bairro: '201' },
  { regiao_saude: 'Região Norte', ra: 'Arapoanga', bairro: 'Arapoanga', descricao: 'Bairro Nossa Senhora de Fátima. Morada Nobre. Núcleo Rural Corrego Atoleiro. Cachoeirinha do Pipiripau. Chácara Bom Sucesso. Setor Habitacional Aprodarmas Etapa I, II, III IV. Condomínios e Residenciais: Arapoanga, Mansões Arapoanga, Chácara do Pequi, Flamboyant, Marissol, Morada Nobre, Nova Esperança, Portal do Amanhecer I, III e V, Prado, Mansões do Amanhecer, Mestre D\'Armas Etapa I e II, Privê Independência, Quintas do Amanhecer I e II, Recanto Feliz, San Sebastian, Sandray, São Francisco, Veneza I, II e III, Vale do Sol, Vila Dimas, Vila Feliz.', id_bairro: '216' },
  { regiao_saude: 'Região Sudoeste', ra: 'Arniqueira', bairro: 'Arniqueiras', descricao: 'Colônia Agrícola: Arniqueira, Vereda Grande', id_bairro: '202' },
  { regiao_saude: 'Região Oeste', ra: 'Brazlândia', bairro: 'Área Rural - Brazlândia', descricao: 'Núcleo Rural: Almécegas, Assentamento Betinho, Barreiro, Bela Vista, Bucanhão, Capão da Onça, Chapadinha, Córrego Olaria, Curralinho, Margem do Pulador, Córrego do Pulador Capãozinho 2 e 3, Radiobrás, Rodeador, Torre. Cascalheira, Incra 6 e 7, Alexandre de Gusmão: gleba 2, rua DF-435.', id_bairro: '262' },
  { regiao_saude: 'Região Oeste', ra: 'Brazlândia', bairro: 'Brazlândia', descricao: 'Brazlândia (toda área urbana), Áreas Especiais, Setor Tradicional: Q 02 a 29, AE 4 e 5, Setor Sul: Q 01, 02, 04, Setor Norte: Qd: 02 a 12, AE 02 e 03 Setor Veredas: Q 01 a 06, Setor de Chácaras,Vila São José.', id_bairro: '263' },
  { regiao_saude: 'Região Oeste', ra: 'Brazlândia', bairro: 'INCRA 8', descricao: 'Incra 8', id_bairro: '264' },
  { regiao_saude: 'Região Oeste', ra: 'Brazlândia', bairro: 'IGN Brazlandia', descricao: 'Null', id_bairro: '265' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Candangolândia', bairro: 'Candangolândia', descricao: 'Candangolândia: Área Urbana. Jardim Zoológico. Setor de postos e motéis norte. Nascente do Lago Paranoá.', id_bairro: '172' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Privê Lucena Roriz', descricao: 'Condomínio Privê Lucena Roriz', id_bairro: '248' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor M Ímpar', descricao: 'QNM ímpares de 1 a 33. AE 1. CNM 1.', id_bairro: '249' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor M Par', descricao: 'QNM pares de 2 a 32. AE 2. CNM 2.', id_bairro: '250' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor N Ímpar', descricao: 'QNN ímpares de 1 a 33. EQNN Ímpares. CNN1.', id_bairro: '251' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor N Par', descricao: 'QNN pares de 2 a 40 (exceto QNN36). EQNN Pares. CNN2', id_bairro: '252' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor O e Expansão', descricao: 'QNO 01 a 23. EQNO.', id_bairro: '253' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor P Norte', descricao: 'QNP ímpares de 5 a 19 (exceto QNP7). EQNP ímpares. Feira do produtor e atacadista de Ceilândia (QNP1). QNN 35, 37 e 39.', id_bairro: '254' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor P Sul', descricao: 'QNP pares de 10 a 36. EQNP pares. QNN 36.', id_bairro: '255' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor R', descricao: 'QNQ 01 a 07. QNR 01 e CNR 01.', id_bairro: '256' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Setor de Indústrias Ceilandia', descricao: 'QNR 02 a 05. QES e QI 01 a 22. Setor de Materiais de Construção Q 1 a 9.', id_bairro: '257' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'Área Rural - Brazlândia', descricao: 'Associação campestre dos policiais do DF - ARC. Condomínios: Arco Verde, Dois Irmãos, Fazenda Água Santa, Jibóia, Laje, Monjolinho, Monte Verde, Quintas do Amarante, Vista Bela. Incra 09 e Núcleo Rural Alexandre Gusmão Gleba 1, 3 e 4. Núcleo Rural Boa Esperança. Rodovia DF-180.', id_bairro: '258' },
  { regiao_saude: 'Região Oeste', ra: 'Ceilândia', bairro: 'IGN Ceilândia', descricao: 'Null', id_bairro: '261' },
  { regiao_saude: 'Região Central', ra: 'Cruzeiro', bairro: 'SHCES', descricao: 'Cruzeiro Novo (SHCES), SRI (Setor Residencial Interno).', id_bairro: '158' },
  { regiao_saude: 'Região Central', ra: 'Cruzeiro', bairro: 'SRES', descricao: 'Cruzeiro Velho (SRES).', id_bairro: '159' },
  { regiao_saude: 'Região Central', ra: 'Cruzeiro', bairro: 'IGN Cruzeiro', descricao: 'Null', id_bairro: '160' },
  { regiao_saude: 'Região Norte', ra: 'Fercal', bairro: 'Area Rural - Fercal', descricao: 'Comunidade Boa Vista. Contagem. Córrego do Ouro. DF- 205, VC-201. Fazenda Ribeirão. Núcleo Rural Catingueiro.', id_bairro: '275' },
  { regiao_saude: 'Região Norte', ra: 'Fercal', bairro: 'Fercal', descricao: 'Fercal Oeste. Fercal Leste. Rua do Mato. Bananal. Queima Lençol. Alto da Bela Vista. Expansão do Alto da Bela Vista. Morro Azul. Engenho Velho. CIPLAN. Votorantim Cimentos.', id_bairro: '276' },
  { regiao_saude: 'Região Norte', ra: 'Fercal', bairro: 'IGN Fercal', descricao: 'Null', id_bairro: '277' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Setor Norte Gama', descricao: 'Setor Norte: Q 1 e 2. Setor de Indústrias (QI 01 a QI 07).', id_bairro: '180' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Setor Sul Gama', descricao: 'Setor Sul', id_bairro: '181' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Setor Leste Gama', descricao: 'Setor Leste. AMBEV e Faciplac.', id_bairro: '182' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Setor Oeste Gama', descricao: 'Setor Oeste. Vila Roriz', id_bairro: '183' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Setor Central Gama', descricao: 'Setor Central. Estádio Bezerrão, Shopping do Gama.', id_bairro: '184' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Ponte Alta Norte', descricao: 'Ponte Alta Norte ou Núcleo Rural Ponte de Terra. Condomínios e residenciais: Açucena, Ágape, Aliança, Athenas, Atlântida, Avenida, Beija Flor, Bougainville, Califórnia, Costa do Sol, Excellence, Filadélfia, Fênix, Florença, Flórida, Garden, Imperium, Innovare, Jerusalém, Lar Ville, Lyrios, Luar do Cerrado, Maestri, Mansões Paraízo, Monte Sinai, Morada Imperial, Morada Nobre, Orion, Parque (Park) do Gama, Piemont, Planalto, Porto Seguro, Porto do Sol, Pomares, Portal do Sabiá, Portinari, Primavera, Recanto do Sabiá, Renascer, Residencial das Palmeiras Paraíso, Royalle, Solar dos Pinheiros, Sonho Meu, Terra Santa, Tom Jobim. Rodovias, avenidas e ruas: Alameda dos Ipês, Avenida Buritis, Avenida São Francisco, Avenida do Sol, DF-341, DF-351, DF-475, Rua Chiara, Rua JK, Rua Juruá, Rua Sucupira, Rua Palmeiras, Rua Dois, Rua Um, Via da Escola.', id_bairro: '185' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Engenho das Lajes', descricao: 'Engenho das Lajes.', id_bairro: '186' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'Área Rural', descricao: 'Adjacência do Setor Oeste e Setor Leste (Rio Alagado, Mansão Paraiso), Cemitério do Gama, Rodovia DF-290 (lado sul da rodovia, BR 060 até GO 520), Ponte Alta de Baixo e Ponte Alta de Cima, Núcleo Rural Ponte Alta (exceto Ponte Alta Norte). Presidio Feminino. Reserva da Aeronáutica, Vargem da Benção', id_bairro: '187' },
  { regiao_saude: 'Região Sul', ra: 'Gama', bairro: 'ING Gama', descricao: 'Null', id_bairro: '188' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Guará I', descricao: 'Guará I. Ímpares QI e QE 01 a 11. Pares QI e QE 2 a 22.', id_bairro: '204' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Guará II', descricao: 'Guará II. Pares: QE 24 a 38, QE 40 (Conjuntos A a G), QE 42 a 46. Ímpares: QE 13 a 25, QI 23 a 33. Área Especial 2 (AE2, AE2A), AE4 e AE10. EQ 13/15 a 42/44. CAVE. 4º BPM PMDF. Terminal Guará II.', id_bairro: '205' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Lúcio Costa', descricao: 'Lúcio Costa (QELC 1/2/3/4).', id_bairro: '285' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Colônia Agrícola Águas Claras', descricao: 'Condomínios e Residenciais: Bela Vista, Bem-Ti-Vi, Buritis, Cecília Meireles, Flor das águas, Flor de Lins, Florisbela, Guará Park, Lírios do Vale, Lobo Guará, Monte Sinai, Morada do Sol, Nolina, Órion, Pôr do Sol, Porto da Vitória Régia, Raios de Sol, Recanto dos Pássaros, Recanto dos Sabiás, Residencial das Palmeiras, Sagrada Família, Santa Bárbara, Shekinah, São Gabriel, Santos Dumont, Solar Park, Super Quadra Brasília (SQB), Terra do Sol, Vale Verde, Verde Perto, Village das Pedras, Vivenda dos Ipês.', id_bairro: '206' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Colônia Agrícola Bernardo Sayão', descricao: 'Polo de Modas. QE 40 (Conjuntos H a R). Setor de Mansões Bernardo Sayão (SMBS).', id_bairro: '207' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Colonia Agrícoa IAPI', descricao: 'Condomínios e Residenciais: Anísio de Assis, Beija Flor, Damasceno, Jardim das Palmeiras, Mendes, Parque do Sabiá, Portal das Oliveiras, Recanto das Pedras, Villa Verde, Yanomani. Bosque dos Eucaliptos. QE: 48, 50, 52, 54, 56, 58.', id_bairro: '208' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'Setor Parque Sul + Reserva Ecológica Guará', descricao: 'CEB, Clube da Saúde, NOS, Novacap, Parque Tecnológico e Industrial da Saúde SES/DF, Secretaria de Educação Unidade III, Secretaria da Fazenda.Park Shopping. Parque Ecológico Ezechias Heringer. Setor de Garagens e Concessionárias de Veículos (SGCV). SMAS trecho 1. SOF Sul (Q1 a Q19).', id_bairro: '209' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Guará', bairro: 'IGN GUARA', descricao: 'Null', id_bairro: '210' },
  { regiao_saude: 'Região Leste', ra: 'Itapoã', bairro: 'Itapoã', descricao: 'Itapoã. Fazendinha. Del Lago.', id_bairro: '229' },
  { regiao_saude: 'Região Leste', ra: 'Itapoã', bairro: 'Condomínio Entrelagos', descricao: 'Condomínio Entrelagos. Privê Residencial La Font.', id_bairro: '230' },
  { regiao_saude: 'Região Leste', ra: 'Itapoã', bairro: 'Área Rural - Itapõa', descricao: 'Parque Hípico de Brasília. Cond. Chacaras Euler Paranhos', id_bairro: '231' },
  { regiao_saude: 'Região Leste', ra: 'Itapoã', bairro: 'IGN Itapoã', descricao: 'Null', id_bairro: '232' },
  { regiao_saude: 'Região Leste', ra: 'Jardim Botânico', bairro: 'Tororó', descricao: 'Condomínios e residenciais: Castelo, Cantinho da Paz, Chapéu de Pedra, Ecológico Parque ou Park do Mirante, Estância Del Rey, Flor do Cerrado, Forte Apache, Mansões Rurais Lago Sul, Mansões Flamboyant, Morada dos Ventos, Privê Lago Sul, Privê Residêncial Mônaco, Quintas Santa Bárbara, Quintas do Trevo, Recanto Bela Vista, Residencial Mirante das Estrelas, Rural Santa Bárbara, San Francisco I e II, Setor Habitacional Tororó, Tropical, . Fazendas e chácaras: Chácara do Tio, Dona Ângela, Manacá, Pé D\'água, Primavera, Recanto das Flores, Recanto das Palmeiras, São Luiz, Sítio Mata Viva, Sítio dos Vegetarianos, Villa Uryel, Santa Maria, Santa Mônica, Santa Bárbara. Núcleo Rural Córrego das Antas. DF-140 chácaras: Anne Cristina e Chácara das Palmeiras', id_bairro: '141' },
  { regiao_saude: 'Região Leste', ra: 'Jardim Botânico', bairro: 'Jardim Magueiral', descricao: 'Condomínios: Jardins dos Jacarandás, Jardins dos Muricis, Jardins das Paineiras, Jardins dos Tinguis, Jardins das Salácias, Jardins do Tapiriris, Jardins dos Jatobás, Jardins dos Angelins, Jardins das Canviúvas, Jardins dos Buritis, Jardins das Mangabeiras, Jardins dos Ipês, Jardins das Acácias. Parque Jardins Mangueiral.', id_bairro: '142' },
  { regiao_saude: 'Região Leste', ra: 'Jardim Botânico', bairro: 'Condominios Jardim Botânico', descricao: 'Altiplano Leste: Privê Morada do Sul, Mini Chácaras do Lago Sul e Quintas da Alvorada I, II e III. Condomínios: AMOBB, Belvedere Green, Ecológico Village (II e III), Estância Jardim Botânico (I e II), Interlagos, Itaipú, Jardim Botânico (I, III, V e VI), Jardim da Serra, Jardins do Lago, Lago Sul I, Mansões Braúna, Mansões Califórnia, Mansões do Itaipú, Mansões Mata da Anta, Mansões Serranas, Maxximo Garden, Mirante das Paineiras, Ouro de Itaipu, Ouro Vermelho (I e II), Parque e Jardim das Paineiras, Portal do Lago Sul, Quintas Bela Vista, Quinta das Colinas, Quintas do Itaipú, Quintas do Sol, Quintas Interlagos, Quintas dos Ipês, San Diego, São Mateus, Solar da Serra, Solar de Brasília, Verde, Vila da Mata, Vila Hípica, Village Alvorada (I e II), Ville de Montagne. Estrada do Sol. Bairro João Cândido. Bairro Residencial São Gabriel.', id_bairro: '143' },
  { regiao_saude: 'Região Leste', ra: 'Jardim Botânico', bairro: 'Papuda', descricao: 'CIR Papuda, CDP (Núcleo de Custódia), CESAMI ( ou CAJE 2), PDF I, PDF II.', id_bairro: '281' },
  { regiao_saude: 'Região Leste', ra: 'Jardim Botânico', bairro: 'IGN Jardim Botanico', descricao: 'Null', id_bairro: '145' },
  { regiao_saude: 'Região Central', ra: 'Lago Norte', bairro: 'Granja do Torto', descricao: 'Torto. Granja Modelo do Torto/Vila Weslian Roriz. Parque de Exposição Agropecuária do Torto. Setor Invernada do Torto (SIT).', id_bairro: '152' },
  { regiao_saude: 'Região Central', ra: 'Lago Norte', bairro: 'Lago Norte/Taquar', descricao: 'Setor Habitacional Taquari (SHTQ). Academia de Polícia. Condomínio Privê II. Núcleo Rural: Boa Esperança II, Córrego do Urubu, Olhos D\'Água. Rural Remanescente do Lago Norte. Setor de Postos e Moteis (SPMN).', id_bairro: '153' },
  { regiao_saude: 'Região Central', ra: 'Lago Norte', bairro: 'Mansões Lago Norte', descricao: 'Setor de Mansões Lago Norte (SMLN). Condomínio Privê I. Fazenda Nossa Senhora da Aparecida. Núcleo Rural: Capoeira do Bálsamo, Córrego Jerivá, Córrego da Palha, Tamanduá B.', id_bairro: '154' },
  { regiao_saude: 'Região Central', ra: 'Lago Norte', bairro: 'Península do Lago Norte', descricao: 'SHIN: QI 01 a 16 e QL 01 a 16, Centro de Atividades (CA).', id_bairro: '155' },
  { regiao_saude: 'Região Central', ra: 'Lago Norte', bairro: 'IGN Lago Norte', descricao: 'Null', id_bairro: '156' },
  { regiao_saude: 'Região Central', ra: 'Lago Sul', bairro: 'Setor Habitacional Individual Sul', descricao: 'SHIS: QI 01 a 28 e QL 02 a 28. Base Aérea de Brasília. Setor de Locadoras.', id_bairro: '137' },
  { regiao_saude: 'Região Central', ra: 'Lago Sul', bairro: 'Setor de Mansões Dom Bosco', descricao: 'SMDB Conjuntos 1 a 31. SHIS QI 25 (Conjuntos 11 a 14), 27, 29. Condomínio do Lago Sul. Jardim Botânico de Brasília.', id_bairro: '138' },
  { regiao_saude: 'Região Central', ra: 'Lago Sul', bairro: 'Villages Alvorada/Ermida Dom Bosco', descricao: 'ARIE Dom Bosco. Mosteiro São Bento de Olinda. Parque Ecológico Dom Bosco. Villages Alvorada I e II. SHIS QI 28 (Conjuntos 1 a 18).', id_bairro: '139' },
  { regiao_saude: 'Região Central', ra: 'Lago Sul', bairro: 'IGN Lago Sul', descricao: 'Null', id_bairro: '140' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Núcleo Bandeirante', bairro: 'Metropolitana', descricao: 'Metropolitana. Setor dos Engenheiros.', id_bairro: '164' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Núcleo Bandeirante', bairro: 'Núcleo Bandeirante', descricao: 'Avenidas: Central, Contorno. Colônias Agrícolas: Núcleo Bandeirante. Placa da Mercedes. Praça Central. Setor Industrial Bernardo Sayão (SIBS). Setor de Postos e Motéis Sul (SPMS). SOPI (Setor de Oficinas e Pequenas Indústrias). Vias EPIA e EPNB. Vila Nova Divinéia.', id_bairro: '165' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Núcleo Bandeirante', bairro: 'Vila Cahuy', descricao: 'Colônia Agrícola NB2. Vila Cahuy.', id_bairro: '166' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Núcleo Bandeirante', bairro: 'IGN Núcleo Bandeirante', descricao: 'Null', id_bairro: '167' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'Área Rural - Paranoá', descricao: 'Altiplano Leste - Sítios: Forquilha, Santos Dumont, São Bartolomeu, Oliveiras, Orquídeas, Via das Acácias, Via Bouganville, Via Caviúna, Via das Harpias, Via João de Barro. Áreas rurais: Boqueirão, Capão da Erva, Capão da Onça, Capão Seco, Cariru, Condomínio Mansões Lago, Desembargador Colombo Cerqueira, Granja Progresso, Itapeti, Jardim II, Lamarão, PAD - DF e DF-120, Rajadinha II (Las Vegas e Chácara Entre amigos), Sobradinho dos Melos, Sussuarana, Três Conquistas. Condomínio São Judas Tadeu. Condomínio Fazendinha.', id_bairro: '223' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'Morada Quintas do Campo', descricao: 'Núcleo Rural Café Sem Troco. DF-130 (a partir da intercessão com a DF-260). Quebrada dos Neres.', id_bairro: '224' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'Paranoá', descricao: 'Espaço Panorama. Hospital regional do Paranoá. Núcleo Rural Tamanduá (Córrego do Tamanduá). Paranoá (Quadras 1 a 35). Parque Vivencial Paranoá. Setor industrial. Vila Giardini.', id_bairro: '225' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'Residencial La Font', descricao: 'Condomínio Privê Residencial La Font (Setor Habitacional Itapoã). Condomínio Parque Boa Esperança.', id_bairro: '226' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'Paranoá Parque', descricao: 'Paranoá Parque.', id_bairro: '227' },
  { regiao_saude: 'Região Leste', ra: 'Paranoá', bairro: 'IGN Paranoá', descricao: 'Null', id_bairro: '228' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Park Way', bairro: 'SMPW Trecho 1', descricao: 'SMPW Quadras 14 a 29. Aeroporto Internacional de Brasília Presidente Juscelino Kubitscheck. Fazenda Água Limpa (UnB). Núcleo Rural Córrego da Onça', id_bairro: '168' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Park Way', bairro: 'SMPW Trecho 2', descricao: 'SMPW Quadras 6 a 13.', id_bairro: '169' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Park Way', bairro: 'SMPW Trecho 3', descricao: 'SMPW Quadras 1 a 5.', id_bairro: '170' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Park Way', bairro: 'Vargem Bonita', descricao: 'SMPW Vargem Bonita.', id_bairro: '171' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Park Way', bairro: 'IGN Park Way', descricao: 'Null', id_bairro: '280' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'Condomínio Planaltina', descricao: 'Condomínio Planaltina. Núcleo Rural Córrego do Arrozal.', id_bairro: '217' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'Condomínio Mestre D Armas', descricao: 'Condomínios e Residenciais: Bica do DER, Cachoeira, Estância, Estância Mestre D\'armas I a V, Estância Planaltina, Girassol, Itiquira, Mansões do Amanhacer, Mansões Itiquira, Mestre D\'armas I e II, Nosso Lar, Nova Esperança, Nova Petrópolis, Nova Planaltina, Park Mônaco I e II, Recanto do Sossego, Rodovia DF-128, Samaúma, Santa Mônica, Sarandy, Setor de Mansões Mestre D\'armas I, Vale do Sol. DVO. Morro da Capelinha: Setor de Chácaras e Mansões Morro da Capelinha.', id_bairro: '218' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'Planaltina Tradicional', descricao: 'Setor Residencial Tradicional Norte (SRTN), Setor Residencial Tradicional Sul (SRTS) ou Vila Vicentina. Setor Residencial Oeste (SRO) ou Vila Nossa Senhora de Fátima. Setor Residencial Norte (SRN/A) ou Jardim Roriz. Setor Residencial Leste (SRL): Buritis (ou Vila Buritis) I, II, III e IV. Horta Comunitária.', id_bairro: '219' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'Vale do Amanhecer', descricao: 'Vale do Amanhecer', id_bairro: '220' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'Área Rural', descricao: 'Núcleo Rural: Assentamento Palmares, Jardins do Morumbi, Rajadinha II e III, Rio Preto,Tabatinga, Taquara.', id_bairro: '221' },
  { regiao_saude: 'Região Norte', ra: 'Planaltina', bairro: 'IGN Planaltina', descricao: 'Null', id_bairro: '222' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'Asa Norte', descricao: 'Avenida das Nações Norte. CAJE. CEUB. Gráfica do Senado. Parque Estação Biológica. Parque Olhos D\'Água. Setor de Administração Federal Norte. Setor de Áreas Isoladas Norte. Setor de Autarquias Norte. Setor de Clubes Esportivos Norte (SCEN) Trecho 2. Setor de Embaixadas Norte. Setor de Grandes Áreas Norte (SGAN). Setor Hospitalar Norte. Setor Hoteleiro Norte. Setor de Mansões Isoladas Norte. Setor de Recreação Pública Norte. Setor Terminal Norte (STN). SQN 102 a 116, 302 a 316, 502 a 516, 702 a 716, 902 a 916. UnB, Colina UnB.', id_bairro: '128' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'Asa Sul', descricao: 'Avenida das Nações Sul. Acampamento Saturnino Brito. Funai. Galeria dos Estados. Hípica. SMAS trecho 3. Setor Policial Sul. Rodoviária interestadual. Instituto Vicenta Maria. Palácio da Alvorada. Praça dos Três Poderes. Setor de Administração Federal Sul. Setor de Clubes Esportivos Sul (SCES). Setor Comercial Sul (SCS). Setor de Diversões Sul. Setor de Embaixadas Sul/Vila Cultural. Setor de Grandes Áreas Sul (SGAS). Setor Hotelereiro Sul. Setor Palácio Presidencial. Setor de Recreação Pública Sul. SQS 101 a 116, 301 a 316, 501 a 516, 701 a 716, 901 a 916. SQS 201 a 216, 401 a 416, 601 a 616. TCU.', id_bairro: '129' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'SMU', descricao: '32º Grupo de Artilharia de Campanha. Batalhão da Guarda Presidencial. Batalhão de Polícia do Exército de Brasília. Catedral Militar do Brasil. Catedral Militar Rainha da Paz. Concha Acústica do Exército. Clube do Exército - SMU. Escola de Inteligência Militar do Exército. Hotel de Trânsito de Oficiais. Paróquia Militar do Oratório do Soldado - São Francisco de Assis. Praça dos Cristais. Quadra Residencial de Generais. Setor de Garagens Oficiais. Praças: Ayrton Senna, Cora Coralina.', id_bairro: '279' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'Vila Planalto', descricao: 'Acampamentos: DFL, Pacheco Fernandes, Rabelo, Tamboril. Fuzileiros Navais. Setor de Hotéis e Turismo Norte (SHTN). Setor de Clubes Esportivos Norte (SCEN) Trecho 1. Setor de Preservação da Vila Planalto.', id_bairro: '133' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'Vila Telebrasília', descricao: 'Vila Telebrasília.', id_bairro: '134' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'Setor Noroeste', descricao: 'Quadras SQNW. Quadras CLNW. Quadras SHCNW. Parque Ecológico Burle Marx.', id_bairro: '135' },
  { regiao_saude: 'Região Central', ra: 'Plano Piloto', bairro: 'IGN Plano Piloto', descricao: 'Null', id_bairro: '136' },
  { regiao_saude: 'Região Sudoeste', ra: 'Recanto das Emas', bairro: 'Área Rural - Recanto das Emas', descricao: 'Área Rural. Núcleo Rural Vargem da Benção chácaras: 14, 16, 17, 37 e 52. Monjolo. DF 280.', id_bairro: '240' },
  { regiao_saude: 'Região Sudoeste', ra: 'Recanto das Emas', bairro: 'Recanto das Emas', descricao: 'Quadras: 101 a 116, 200 a 206, 300 a 311, 400 a 407, 508 a 511, 600 a 605, 800 a 804.', id_bairro: '241' },
  { regiao_saude: 'Região Sudoeste', ra: 'Recanto das Emas', bairro: 'IGN Recanto das Emas', descricao: 'Null', id_bairro: '243' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo I', bairro: 'Riacho Fundo', descricao: 'Granja Modelo. QN: 1, 3, 5, 7, 9. QS: 2,4,6,8,10,12,14. Regimento da Polícia Montada.', id_bairro: '173' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo I', bairro: 'Colônia Agricola Sucupira + Cond. Riacho Fundo', descricao: 'Colônias Agrícolas: Riacho Fundo, Sucupira. Condomínio Califórnia. Fazenda Sucupira. Kanegae. QS 16', id_bairro: '174' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo I', bairro: 'IGN Riacho Fundo I', descricao: 'Null', id_bairro: '175' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo II', bairro: 'Riacho Fundo II', descricao: 'QC: 1, 2, 4 E 6. QN: 5A a C, 7A a 7F, 8A a 8F, 9A a 9B, 10, 11, 12, 14A a F, 15A a F, 16, 18, 19, 24, 29, 30, 32, 33. QS: 1 a 18 . CAUB I e II. Colônia Agrícola Catetinho.', id_bairro: '176' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo II', bairro: 'Riacho Fundo Parque', descricao: 'Condomínios: Buriti, Ipê Amarelo, Ipê Roxo. Anexo da Administração Regional do Riacho Fundo II.', id_bairro: '177' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo II', bairro: 'Área Rural - Riacho Fundo II', descricao: 'Colônia Agrícola Sucupira: Chácara 35/37,condomínio Ave Branca, Rancho Imperial 33, Recanto dos Pássaros. Condomínio Granja Modelo 3. Entorno CAUB I e II.', id_bairro: '178' },
  { regiao_saude: 'Região Centro-Sul', ra: 'Riacho Fundo II', bairro: 'IGN Riacho Fundo II', descricao: 'Null', id_bairro: '179' },
  { regiao_saude: 'Região Sudoeste', ra: 'Samambaia', bairro: 'Área Rural - Samambaia', descricao: 'Área Isolada Guariroba. Aterro Sanitário de Brasília. Caesb ETE Melchior. JBS Foods - Seara Alimentos. Núcleo Rural Taguatinga.', id_bairro: '244' },
  { regiao_saude: 'Região Sudoeste', ra: 'Samambaia', bairro: 'Samambaia 100 300 500', descricao: 'Samambaia Sul. ADE Samambaia. Colônia Agrícola Veredas. Setor de Mansões Sudeste (SMSE). Centro Urbano. Quadras 101 e 301. Subestação Brasília Sul. QN, QR, QS: Quadras 100, 300 e 500.', id_bairro: '245' },
  { regiao_saude: 'Região Sudoeste', ra: 'Samambaia', bairro: 'Samambaia 200 400 600 800', descricao: 'Samambaia Norte. Condomínio Nova Vida. QN, QR, QS: Quadras 200, 400 e 600. Quadras: 827, 829, 831, 833, 1029, 1031, 1033. QI 416 e 616.', id_bairro: '246' },
  { regiao_saude: 'Região Sudoeste', ra: 'Samambaia', bairro: 'IGN Samambaia', descricao: 'Null', id_bairro: '247' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Área Rural - Santa Maria', descricao: 'Núcleo Rural Santa Maria: Avenida Perimetral do Distrito Federal, Cachoeira das Três Quedas, Cachoeira Trilha Buritis, Centro de Instrução e Adestramento de Brasília, Condomínio de Chácaras Ana Maria, Lagoa das Araras, Polícia Rodoviária Federal, Rio Alagado, Saia Velha, Vila Naval Almirante Visconde de Inhaúma (VNAVI).', id_bairro: '233' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Condominios Santa Maria', descricao: 'Setor Habitacional Ribeirão, Condomínio Porto Rico.', id_bairro: '234' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Residencial Santos Dummont', descricao: 'Residencial Santos Dumont, Av. Santos Dumont. QR 120, 121, 122.', id_bairro: '235' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Santa Maria', descricao: 'Santa Maria Sul: QR, AC, CL e EQC 100 a 111,200 a 211, 300 a 311, 401 a 411. Qd Central 1 e 2. Santa Maria Norte: QR, AC, CL e AQ 112 a 119, 212 a 218, 312 a 318, 415 a 418, 516 a 518.', id_bairro: '236' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Vila DVO', descricao: 'Vila DVO.', id_bairro: '237' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'Residencial Total Ville', descricao: 'Residencial Total Ville. Setor Meireles. Polo de desenvolvimento JK.', id_bairro: '238' },
  { regiao_saude: 'Região Sul', ra: 'Santa Maria', bairro: 'IGN Santa Maria', descricao: 'Null', id_bairro: '239' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'Área Rural - São Sebastião', descricao: 'Núcleo Rural: Nova Betânia, Aguilhada, Cachoeirinha, Cava de Baixo, Cava de Cima. DF - 130.', id_bairro: '146' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'Morro da Cruz', descricao: 'Área Isolada Papudas. Assentamento Recanto da Conquista. Encontro da DF-473 com a BR-251. Núcleo Rural Morro da Cruz. Ruas Perimetral: 57, 58, 59, 60, 61, 62.', id_bairro: '147' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'Núcleo Rural Capão Comprido', descricao: 'Núcleo Rural Capão Comprido. Encontro da DF-473 com a BR-251. Rio São Bartolomeu.', id_bairro: '148' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'São Sebastião', descricao: 'Bairros: Bonsucesso, Centro, Morro Azul, Residencial Bela Vista, Residencial Bora Manso, Residencial do Bosque, Residencial Oeste, Residencial Vitória, São Bartolomeu, São José, São Francisco, Setor Tradicional, Vila do Boa, Vila Nova.', id_bairro: '149' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'Residencial Crixás', descricao: 'Condomínio Crixás.', id_bairro: '150' },
  { regiao_saude: 'Região Leste', ra: 'São Sebastião', bairro: 'IGN São Sebastião', descricao: 'Null', id_bairro: '151' },
  { regiao_saude: 'Região Centro-Sul', ra: 'SCIA / Estrutural', bairro: 'Vila Estrutural + Cidade dos Automóveis', descricao: 'Quadras da Estrutural (SOES, Setor Norte, Leste, Oeste, Central, Especial). Cidade do Automóvel.', id_bairro: '211' },
  { regiao_saude: 'Região Centro-Sul', ra: 'SCIA / Estrutural', bairro: 'Chácara Santa Luzia', descricao: 'Casa de Paternalidade. Centro Social Santa Clara. Chácara Santa Luzia (Qd 17). Cruzamento DF-097 com DF-010. Igreja Pentecostal Jesus é Vida.', id_bairro: '212' },
  { regiao_saude: 'Região Centro-Sul', ra: 'SCIA / Estrutural', bairro: 'Área Rural - SCIA', descricao: 'Colônia Agrícola Cabeceira do Valo. Ruas sem fim à esquerda da última avenida da SCIA. Referência: Chácara Toca da Coruja.', id_bairro: '213' },
  { regiao_saude: 'Região Centro-Sul', ra: 'SCIA / Estrutural', bairro: 'IGN Estrutural', descricao: 'Null', id_bairro: '214' },
  { regiao_saude: 'Região Centro-Sul', ra: 'SIA', bairro: 'SIA', descricao: 'SIA. Setor de Armazenagem e Abastecimento Norte (SAAN). Setor de Oficinas Norte (SOFN). Setor de Transportes Rodoviários e de Cargas (STRC). Setor de Inflamáveis (SIN). QELC/VILA TECNOLÓGICA. Regimento de Cavalaria de Guardas (RCG). Setor Militar (SMC).', id_bairro: '215' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho', bairro: 'Área Rural - Sobradinho', descricao: 'Condomínios: Alto da Boa Vista, Serra Verde. Assentamento Palmares. Chácara São Marcos. DF440. Estância El Negro. Horto Florestal. Núcleos Rurais: Capão da Erva, Lobeiral e Sobradinho II. Sonhém de Cima. Parque Rodoviário do DER. Parque Vivencial de Sobradinho. Rota do Cavalo. Zona Rural de Sobradinho.', id_bairro: '266' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho', bairro: 'Condomínio RK', descricao: 'Condomínios: Império dos Nobres, RK.', id_bairro: '267' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho', bairro: 'Nova Colina', descricao: 'Condomínios e Residenciais: Asa Branca, Bom Jesus, Bela Vista Serrana, Lara, Morada Colonial, Nova Colina I e II, Nova Dignéia I/II/III, Novo Oriente, Novo Setor de Mansões, Petrópolis, Uberaba, Vivendas Recanto da Serra.', id_bairro: '268' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho', bairro: 'Sobradinho', descricao: 'Quadras: 1 a 18. Quadra Central. Setores: Industrial, Hoteleiro, Expansão Econômica, Oficinas.', id_bairro: '269' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho', bairro: 'IGN Sobradinho', descricao: 'Null', id_bairro: '274' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho II', bairro: 'Area Rural - Sobradinho II', descricao: 'DF-205 até Fercal Oeste. Quebra dos Deuses. Parque Nacional (acima da DF-001). Entorno da Fercal. Condomínio Serra Azul.', id_bairro: '271' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho II', bairro: 'Lago Oeste', descricao: 'Lago Oeste: Ruas 0 a 25. Condomínio Vila Basevi.', id_bairro: '272' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho II', bairro: 'Sobradinho II', descricao: 'Sobradinho II, AR 01a28, Av. Central. Polo de Cinema. Setor de Mansões Sobradinho e adjacentes. Condomínios da DF150, DF215 e DF425: Setor Habitacional Contagem - Condomínios e Residenciais: Alvorecer dos Pássaros I/II, Bem Estar, Boa Sorte, Caravelo, Casa Rosada, Contagem, Fraternidade, Halley, Ipês, Jardim América, Jardim Ipanema, Jardim Vitória, Mansões (ou Mansões Sobradinho II), Marina, Meus Sonhos, Morada, Novo Horizonte, Paraíso, Planalto, Recanto do Mené, Recanto dos Nobres, Rio Negro, São José, Serra Dourada (I/II), Sobradinho (I/II/III), Sol Nascente, Versales (ou Versalhes), Vila Centro Sul, Vila Rica, Vila Verde, Vivendas Alvorada I/II, Vivendas Beija Flor, Vivendas Campestre, Vivendas Paraíso, Vivendas da Serra. Chácaras: Beija Flor, Buritizinho, Chácara do Sossego, Harmonia, Paraíso, Paranoazinho, Terapia. Setor Habitacional Boa Vista - Condomínios e Residenciais: Bianca, Café Planalto, Granville, Morada dos Nobres, Nosso Lar, Park Colorado (ou Parque Colorado), Por do Sol, Recanto Real, Sítio dos Anjos, Vivenda Serrana,2001. Ruas: DF-001 KM 132, DF-150 KM 02, DF-020 KM 2/2, DF-425 KM 01. Setor Habitacional Grande Colorado - Condomínios e Residenciais: Colorado Ville, Jardim Europa (I/ II), Mansões Colorado, Solar de Athenas, Vivendas Bela Vista, Vivendas Colorado (I/II), Vivendas Friburgo, Vivendas Lago Azul Setor de Mansões Sobradinho - Condomínios e Residenciais: Chácara da Serra Real, Comercial e Residencial, Fibral, João de Barro, Mansões Sobradinho, Mini Chácaras, Mirante da Serra, Morada da Serra, QMS 44, Q 51 A, Serra Azul, Sobradinho Novo, Vale das Acácias, Vale das Sucupiras, Vale do Sol, Vale dos Pinheiros, Verde Vale, Vila Rabelo.', id_bairro: '273' },
  { regiao_saude: 'Região Norte', ra: 'Sobradinho II', bairro: 'IGN Sobradinho II', descricao: 'Null', id_bairro: '270' },
  { regiao_saude: 'Região Oeste', ra: 'Sol Nascente/ Pôr do Sol', bairro: 'Sol Nascente', descricao: 'QNP ímpares de 21 a 29. Setor Habitacional Sol Nascente (SHSN). Condomínios: Beija-flor, Brasil, Cachoeirinha, Casa Branca, Embaré I, Gênesis, Horta Comunitária, Maranata, Novo Horizonte, Pedra Verde, Residencial (Acácias, Eldorado, Pinheiros, Vitória, Gileade) Rio Verde, Vargem da Vitória, Vila Madureira, 5 Estrelas. Ruas: Cascalheira, Rua Macalão (Zélia Macalão),Treze de maio. Chácaras: Alvorada, Arneiro 7, Batista, Mota ,Padre Cícero, Rosa, Santo Antônio, Santos, São Cosmo, São José, São Francisco, São Raimundo, Tupinambás. Chácara Sagrada: 123, 124, 125, 125A, 126, 127, 127A, 127B, 128, 128A, 128C, 131, 132, 133A, 133B, 134, 135, 135A, 135B, 136, 136 A/B, 136A, 137, 139, 139A, 139B, 140, 141, 141A, 142A, 143, 144, 144C, 146, 148, 149, 149A, 150, 151, 151A, 151C, 152, 157, 157A, 157B, 160, 160A, 160C, 160D, 162, 164, 165, 167, 171. Nossa Senhora Aparecida: 97 e 98A, 98, 98A, 99, 100, 101, 101A, 101C, 105A, 107, 107A, 108B, 109/110, 109B, 110, 111, 111A, 111C, 111D, 112, 113, 115, 117, 118, 119, 120, 120/121, 121, 122, 123. Nossa Senhora de Fátima: 12A, 13, 13A, 14. Nunes: 47, 48, 50, 51, 51A, 51B. Primavera: 191, 192A, 194, 195, 200, 200A, 201, 203, 203A, 204, 206, 355, 356. Rainha: 52B, 53, 57, 58, 58/123A, 61, 64, 65, 66, 67, 67A, 67B, 69, 73, 73B, 74, 75. Santa Luzia: 1, 2, 3, 3C, 4, 5, 5A, 6, 7, 7A, 8, 9, 10, 11, 12. Santa Rita: 14A, 14B, 14C, 15, 15A, 15B, 16, 17, 17A, 18, 19, 20, 21, 21A, 21B, 22, 22/20, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 36, 36B, 37, 37B, 39, 40, 41A, 41B, 41D, 42, 42A, 43, 43D, 43G, 45, 45A, 45C, 45D, 46, 46B. São João: 78, 79. Rezende: 80, 81, 81/2, 84, 85, 86, 87, 89, 91, 91A, 91D, 92, 92A, 92B, 94, 94A, 95A, 96, 96A, 97, 97/10B. Rio Verde: 172, 178, 181, 185, 185A, 186, 187. Três irmãos: 411, 616.', id_bairro: '259' },
  { regiao_saude: 'Região Oeste', ra: 'Sol Nascente/ Pôr do Sol', bairro: 'Pôr do Sol', descricao: 'Setor Habitacional Pôr do Sol (SHPS) - Chácaras: Dom Bosco 83A, São Francisco de Assis, Santa Luzia 86. Área de Desenvolvimento Econômico (ADE) Pró-DF Qd 01 a 04. Núcleo Rural de Ceilândia: Chácara 76, 94, 110, S/N. Quadra: 100 a 108, 201 a 208,302 a 304, 401 a 402, 501 a 504, 501A e B, 601 a 603, 701 a 703, EQ 500/700. Residenciais: Pôr do Sol, Sarah Kubitschek, União, Vivendas.', id_bairro: '260' },
  { regiao_saude: 'Região Sudoeste', ra: 'Taguatinga', bairro: 'Taguatinga Norte', descricao: 'Centro (C1 a C11): QNA, CNA, QNB, CNB, QNC, CNC, QNF, CNF, CRT, QND, QNE, QI, QNG, CNG, QNH, CNH. Centro Administrativo do DF. Floresta Nacional de Brasilia (Flona) + Área Institucional Taguatinga. Estádio Elmo Cerejo, Rodoviária de Taguatinga, Serejinho, 17ª DP Tag Norte. SAGOCAN (Residencial Reserva Taguatinga: Itamaraty, JK e Esplanada. Setor M Norte (QNM e EQNM pares 34 a 42): Setor Comercial, Shopping JK, QNJ, QNL, SOF (A,B,C,D e E), Setor Comercial, SIG de Taguatinga. Setor de Desenvolvimento Econômico: SDE 01, 02, 03. Quadras Centrais Norte.', id_bairro: '189' },
  { regiao_saude: 'Região Sudoeste', ra: 'Taguatinga', bairro: 'Taguatinga Sul', descricao: 'AE, Carrefour, Centro (C6 a C12), CSC, CSD, CSE, CSF, CSG, Extra, Invasão do Extra, QSA, QSB, QSC, QSD, QSE, QSF, QSG, QS1, QS3, QS5, Taguatinga Shoping.', id_bairro: '190' },
  { regiao_saude: 'Região Sudoeste', ra: 'Taguatinga', bairro: 'Chacaras Taguatinga + Primavera', descricao: 'Parque Onoyama. Setor de Chácaras (QSC 19). Setor de Mansões Taguatinga. Setor Primavera. Sítio Geranium.', id_bairro: '191' },
  { regiao_saude: 'Região Sudoeste', ra: 'Taguatinga', bairro: 'IGN Taguatinga', descricao: 'Null', id_bairro: '192' },
  { regiao_saude: 'Região Central', ra: 'Varjão', bairro: 'Varjão', descricao: 'Varjão, Núcleo Rural do Torto (Chácaras Varjão do Torto).', id_bairro: '157' },
  { regiao_saude: 'Região Sudoeste', ra: 'Vicente Pires', bairro: 'Colônia Agrícola Vicente Pires', descricao: 'Vicente Pires Chácaras 01 a 335', id_bairro: '193' },
  { regiao_saude: 'Região Sudoeste', ra: 'Vicente Pires', bairro: 'Colônia Agrícola Samambaia', descricao: 'Colônia Agrícola Samambaia', id_bairro: '194' },
  { regiao_saude: 'Região Sudoeste', ra: 'Vicente Pires', bairro: 'Colônia Agrícola São José', descricao: 'Colônia Agrícola São José', id_bairro: '195' },
  { regiao_saude: 'Região Sudoeste', ra: 'Vicente Pires', bairro: '26 de Setembro', descricao: 'Colônia Agrícola 26 de Setembro. Mansão das Hortências. Colônia Agrícola Cana do Reino.', id_bairro: '196' },
  { regiao_saude: 'Região Sudoeste', ra: 'Vicente Pires', bairro: 'IGN Vicente Pires', descricao: 'Null', id_bairro: '197' },
  { regiao_saude: 'Região Central', ra: 'Sudoeste/Octogonal', bairro: 'Octogonal', descricao: 'AOS 01 a 08.', id_bairro: '161' },
  { regiao_saude: 'Região Central', ra: 'Sudoeste/Octogonal', bairro: 'Sudoeste', descricao: 'SQSW: 100a105, 300a306 e 504, QMSW 1a6, CCSW 1a6, QRSW 1a8, Setor de Oficinas do Sudoeste. Setor de Indústrias Gráficas (SIG).', id_bairro: '162' },
  { regiao_saude: 'Região Central', ra: 'Sudoeste/Octogonal', bairro: 'IGN Sudoeste/Octogonal', descricao: 'Null', id_bairro: '163' },
  { regiao_saude: 'Ignorado', ra: 'Ignorado', bairro: 'IGN DF', descricao: 'Null', id_bairro: '82' }
];

export const getGeoByCode = (code: string): GeoLocation | undefined => {
  return DF_GEO_DB.find(geo => geo.id_bairro === code);
};

export const suggestGeoByAddress = (address: string, district: string): GeoLocation | undefined => {
  const searchTerms = (address + ' ' + district).toLowerCase();
  
  // Scoring system to find best match in descriptions
  let bestMatch: GeoLocation | undefined;
  let maxScore = 0;

  for (const geo of DF_GEO_DB) {
    if (geo.descricao === 'Null') continue;
    
    const keywords = geo.descricao.toLowerCase().split(/[.,:;\s]+/).filter(k => k.length > 3);
    let score = 0;
    
    // Check main Bairro name
    if (searchTerms.includes(geo.bairro.toLowerCase())) score += 10;

    // Check keywords in description
    for (const word of keywords) {
      if (searchTerms.includes(word)) score += 1;
    }

    if (score > maxScore && score > 2) { // Threshold
      maxScore = score;
      bestMatch = geo;
    }
  }

  return bestMatch;
};
